### ISSUE TITLE
Investigate how to best show translated error messages thrown by the backend

### ISSUE THREAD

**Issue by nlitwin** [Journaly/journaly#106]
#### What

- Investigate how to best show translated error messages thrown by the backend

#### Why

- Since the backend throws errors with corresponding error messages, the user will need to see that error message localized for them

#### How

- One solution that keeps the infra much simpler is to just send an error code from the backend and use the error code as the key to the translation. Open question:

1. Would logs just include the error code? or the error message in english as well? (We need to have one source of truth for the text in English)

Alternate solution that adds a lot more infra and complexity:

- We could move our translation files that currently sit in `/journaly/frontend/public/static/locales/**/*.json` into `/journaly`, then `/journaly/backend` could access them too. We'd need to think about how to:

1) Move `.json` files out of frontend and not break it
1) Access the user's locale on a given API request
1) Retrieve the translated text from `journaly/backend`

**Comment by nlitwin** [comment]
@robin-macpherson Using error codes definitely seems like the way forward. I'm wondering if it's ok to only include the error code in server log messages, or if we also need to include the english translation? The pro for only using error codes means that the infrastructure stays very simple and all the `*.json* files can stay in `/journaly/frontend/public/static/locales/**/*.json`. If we also want to include the error text in the logs, we'll need to add extra logic and/or infrastructure to support accessing the translation JSON files from the backend as well

**Comment by robin-macpherson** [comment]
In my mind, the backend errors that we throw are also instrumental for our work monitoring and debugging code. These are things that will eventually be sent to a logging platform and will be super important for developers, so that's why my thought was throwing errors on the backend that are very helpful and descriptive for debugging purposes but including that code that can be used to map that error to the appropriate client-facing error message that will also be supported by our translation infrastructure

**Comment by robin-macpherson** [comment]
I feel like it would be so painful and even just unworkable if our backend logs are just full of codes like that and we had to go and reference something else to figure out what each one was.
