### ISSUE TITLE
Add editor UI for headings

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#175]
#### Perceived Problem

Currently it's not possible to add headings in the editor, this is something we have in seed data and would be nice for users to be able to do as well. May or may not require server side changes to support, but should be simple copy-paste of the existing header level(s)

#### Ideas / Proposed Solution(s)

Add buttons for h2-h4 to the editor UI

**Comment by robin-macpherson** [comment]
I originally wrote support for all the headings and then after I realized that the title is the main title of the post (which displays in the header with the image) and that then, most people probably won't need much more than secondary headers (like sub-headings for the post). So that's why in the interest of keeping the rich text editor toolbar as simple as possible, I just added that single button for adding those headings, which personally I think is fine -- what do you think?

I did notice recently when testing out the editor that this appears to be another thing that wasn't updated properly when the design system/theme was implemented, as the size doesn't really change much, and I've been meaning to improve that. I can do that today
