### ISSUE TITLE
Favico is very hard to see against light tab colors

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#227]
#### Description

Favico is light, on light browser themes it is very hard to see. See screenshot:

![Screen Shot 2020-08-02 at 4 15 36 PM](https://user-images.githubusercontent.com/2343714/89132695-99b62980-d4db-11ea-9e94-962f7d26461a.png)

We can either add an outline to the "J" or make the background dark rather than transparent

**Comment by xferguson** [comment]
I noticed this when I tried to add the Journaly page to my phone's home screen.

![Screenshot_20201102-085402](https://user-images.githubusercontent.com/3017993/98117474-105e1c80-1e67-11eb-9d56-9541e86c0856.png)

I also noticed this issue doesn't have a card on the kanban. How can I start editing the kanban to create notes / convert notes to issues?

**Comment by robin-macpherson** [comment]
Wow good find! Hmm so I set things up so that issues would automatically be added to the kanban when you create an issue, and then when a PR is linked that card should automatically be moved to "in progress" and then when it is merged/closed it is marked as "done". Next time you see something, let's have you create an issue and monitor what happens

**Comment by robin-macpherson** [comment]
@xferguson did you want to work on this?

**Comment by xferguson** [comment]
@robin-macpherson -- I'm not sure I have a decent image editor to do that anymore. I'm stuck with Paint.

**Comment by robin-macpherson** [comment]
> @robin-macpherson -- I'm not sure I have a decent image editor to do that anymore. I'm stuck with Paint.

Haha good ole Paint. I'll try to make some time for this soon
