### ISSUE TITLE
Add aliases

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#250]
#### Perceived Problem

- it's a pain in the ass to import stuff

#### Ideas / Proposed Solution(s)

- Alias:
  - `@components`
  - `@hooks`
  - `@generated`
  - etc.

**Comment by robin-macpherson** [comment]
@nlitwin would you be able to take this one? I feel like you're an aliasing badass!

**Comment by nlitwin** [comment]
haha sure thing!

**Comment by davidsonsns** [comment]
Hi guys! I'd like to get this one. Just saw that the pr #307 is stuck, so, it could be a good one to challenge me. 

About the alias names, my guess is that we could rename it to `@/hooks` instead of e.g `@hooks`. By doing that we could easily avoid relate it to project packages, e.g `@journaly/j-db-client`.

Sounds good?

**Comment by robin-macpherson** [comment]
Hi @davidsonsns, thanks for wanting to pick this up! You're welcome to take it 🙂

Hmm that's a good thought regarding the alias names. If you can make that work then I think that's fine!
