### ISSUE TITLE
Upgrade Nexus from v0.25.0 to v0.27.0 to enable Windows support

### ISSUE THREAD

**Issue by xferguson** [Journaly/journaly#370]
#### Description

It turns out I can't run `npm run build` on my machine because [Nexus@0.25.0 doesn't support Windows CLI](https://github.com/prisma-labs/graphql-framework-experiment/issues/965#issuecomment-645485119). They [released Windows support in July](https://github.com/prisma-labs/graphql-framework-experiment/pull/1184), and we could upgrade to the [Latest (0.27.0)](https://github.com/prisma-labs/graphql-framework-experiment/compare/0.25.0...0.27.0) which should work.

#### Repro Steps

1. Open a terminal on windows and run `npm run build`
2. **Expected**: The build should run and pass
3. **Actual**: The script will fail with an error: `The global Nexus CLI you invoked could not hand off to your project-local one becuase it wasn't on disk.`

**Comment by xferguson** [comment]
I'm working on this first to ensure I can run that `npm run build`, and will open a PR soon (hopefully)

**Comment by xferguson** [comment]
@Lanny @robin-macpherson I did the upgrade, but when I tested the `npm run build` I got this GraphQL error:

```
Error: nexus/post.ts:34:26 - error TS2322: Type '"PostTopic"' is not assignable to type '"ERROR: No subset types are available. Please make sure that one of your GraphQL type is a subset of your t.model('<ModelName>')" | undefined'.

34     t.model.postTopics({ type: 'PostTopic' })
```
Pretty weird, as I can see `PostTopic` defined 20 lines above it. Maybe it makes sense to one of you, but I will take a look at this again tomorrow when I have more time to code 😄

**Comment by robin-macpherson** [comment]
@xferguson sorry for the delay getting back to you here, it's been a crazy couple of days! Hmm that error a bit strange, I haven't had a chance to look too closely yet but did you already check the release notes for the versions to see if there were any breaking changes? Since we were using the Nexus Framework at a very early stage, things were a little less stable between releases. That should be much better once we migrate off of it soon.

I can take a closer look tomorrow if you're still stuck 😊

**Comment by Lanny** [comment]
I tried upgrading on OSX and was not able to repro, although I hit a few stumbling blocks around actually getting the appropriate versions of things to install. Had to pin nexus and nexus-plugin-prisma to specific versions, it doesn't seem like these projects follow semver and because we had `nexus-plugin-prisma": "^0.9.0",` previously I got bumped all the way up to 0.23 which seems to be incompatible with nexus 0.26 (chose that one because it was the first release with windows support, allegedly). My diff on package.json looked like:

```diff
-    "nexus": "^0.25.0",
-    "nexus-plugin-prisma": "^0.9.0",
+    "nexus": "0.26.0",
+    "nexus-plugin-prisma": "0.9.0",
```

Could you try with 0.26 and no `^`s to see if the error you're getting is fallout from the versions get resolved?

**Comment by robin-macpherson** [comment]
Ah yes great point @Lanny, I forgot that I had also had some problems with version compatibility between those dependencies when performing upgrades in the past. I guess ultimately it will be nice that after migrating off of Nexus framework everything should be a lot more stable 🤞🏼

**Comment by xferguson** [comment]
I took a swing at @Lanny's advice -- no change. I was digging into this some, and it looks like this could be related to nexus/schema specifically. Found an unresolved issue with the same error I'm getting: https://github.com/graphql-nexus/schema/issues/435

I also noticed some warnings in my `npm install`:
```npm WARN next-i18next@6.0.2 requires a peer of next@>= 9.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN nexus-prisma@0.14.0 requires a peer of @nexus/schema@^0.13.1 || ^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package @types/express is included as both a dev and production dependency.
npm WARN The package @types/node is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

Those first two could be related. Frankly, I've never dealt with nexus or next, and my GraphQL experience has been pretty rudimentary, off of a docker container that already had some boilerplate in there, so this may take me a while to dig into.

**Comment by robin-macpherson** [comment]
Hmm I see 😕 I wonder if it's better to table this for the time being then, since we'll be migrating off of Nexus framework soon and that may change some things and make it easier to get these peer dependency issues sorted out since we'll be managing all of our Prisma and Nexus stuff ourselves then. It's a shame that you're stuck on this 😕 We can try to bump the migration off of Nexus up and get that done soon

**Comment by xferguson** [comment]
I'm cool with spending a little more time looking at this. The biggest issue is that this is a blocker to me running `npm run build`.

I can't speak to how much of a lift it is to do the migration off of Nexus, but I imagine that's non-trivial.

_On one hand_, better to do it now while you have less code coupled with it. _On the other hand_, you are trying to move a lot forward right now and are short on people to do it. Moving the `build` script into something like TravisCI may be a good alternative. With the right integrations set up, the build would be handled and verified before the PR, which would mean people wouldn't have to do it, but we could still see if the build failed and get good logs on why.

Unfortunately, I haven't a lot of experience with Git+Travis, so I wouldn't claim to be able to estimate that task 🤣 [This blog post](https://blog.travis-ci.com/2019-05-30-setting-up-a-ci-cd-process-on-github) makes it look like the integration steps are minimal and there would only be a short configuration file to write, but experience tells me not to underestimate devops...

**Comment by xferguson** [comment]
^ Or CircleCI, as I see you are already starting to toy with it.

**Comment by Lanny** [comment]
FWIW I tried setting things up on windows yesterday, ran into the same issue, and wasn't able to figure out why nexus didn't seem to be picking up on the `PostTopic` type. It does feel like something that kicking the nexus framework dependency would fix, or at least shed some light on why it doesn't work. Now might be the time to do it since we have a handful of things where we could really use prisma upgrades that this work blocks (#334, the raw SQL hack badges has to use, etc.), and it might make sense to do at the same time as the work @robin-macpherson is doing with pulling the DB client out into its own package.

Setting up circle to run the build through circle isn't the ideal solution to this, being able to run the build locally is something developers really should be able to do. But it would be a short term solution and wouldn't be throw away work since it's a nice sanity check to be able to run against PRs, plus it's a step toward moving the deploy process away from "read the PR, figure out what series of commands to run, do them locally".

The circle part should be easy, I can definitely get that done this week. I think I'll take a stab at migrating off the nexus framework dependency too, but it's possible it's a rabbit hole, so we'll see how it goes.

**Comment by Lanny** [comment]
@xferguson #390 set up CI for building in circle. Now onto the white whale of the nexus dependency.

**Comment by robin-macpherson** [comment]
Amazing thanks so much @Lanny ! Go get that white whale! ⇀  (that's a harpoon lol)
