### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by nlitwin** [Journaly/journaly#40]
#### Perceived Problem

- We need to make sure we are collecting analytics data in order to gain insight into where our users are coming from and how pages are visited, and to inform future tests and decisions.

#### Ideas / Proposed Solution(s)

-  Set up Google Analytics

#### Requirements

- Set up proper event tracking on each page so that we control the events and can better use that data

**Comment by robin-macpherson** [comment]
Hey @nlitwin , I actually already working on this yesterday since the `journaly.com` site started to get a tiny bit of traffic after the Prisma Interview session and I'll be recording a video today with Journaly updates and will mention that we got the dot com and so I imagine some people will try visiting that page, so wanted to knock it out quickly. Came to create an issue and saw this one 🙂
