### ISSUE TITLE
Have a way to track one's activity

### ISSUE THREAD

**Issue by rickyweb** [Journaly/journaly#437]
#### Perceived Problem

Currently, it's hard to track one's activity. I'm unable to find
- which posts I corrected or commented
- in which comments my name was mentioned (using @username doesn't seem to have any effect -- Build @mentioning #443)
- which posts of mine received new corrections or comments
The third point was partly covered by the e-mails I used to receive, but now this somehow has changed into a digest e-mail which probably doesn't cover everything. It would be good to be able to set up the e-mail type (every notification, digest notification, nothing) -- but that should probably go into a separate feature request. => Daily Digest Email Improvements #460

#### Ideas / Proposed Solution(s)

- In order to see which posts I corrected or commented, one could add a new filter in "My Feed" called "My interactions"
- Next to my username, there could be a notification bell with the number of "unseen" replies to comments in other users' posts, new corrections or comments to my posts. Clicking on the bell would load a page that would list the notifications and show which ones are "read" and which ones "not yet read". (see also In-App Notifications #380)
- In the "My Posts" page,  next to the "comments" symbol, there is currently a number of comments overall. One could split that in two numbers (total comments/unread comments -- if any), the latter would be bold.

Thanks Robin for looking into this, that would immensely increase the UX of the app!

**Comment by robin-macpherson** [comment]
Thanks for this issue @rickyweb ! I think this is a good point, I'll have to think about what a good visual design and User Experience would be. I like the idea of using the my feed filters as a way to do this, since there could eventually be quite sophisticated filter settings there! I'm also glad to see that some of the issues on the roadmap will help with this.

The daily digest email should cover all of your new comments or corrections - the only thing that has lost some granularity right now is the "thanks", as now the daily digest will just show how many thanks you received. I think we can get this granularity back with #380 thankfully. And, ultimately, it will be fantastic once we have the really nice and granular notification settings so that each user can tailor them to their own preferences.

I'm really excited to get lots of great suggestions and to work on them little by little! 😄

**Comment by rickyweb** [comment]
Yeah, don't get any stress because I'm writing bug reports and feature requests. I know we're beta users and I have a lot of understanding for the not yet perfect state of the software. It is awesome so far and very well usable!

**Comment by robin-macpherson** [comment]
Update: #615 (posts I've commented on - history filter action) is in progress and handle the first point, and #380 is on the roadmap to be tackled shortly afterwards which will handle the third point 🔥
