### ISSUE TITLE
EDITOR: Add hyperlink capability

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#440]
#### Perceived Problem

- Currently, users cannot add hyperlinks to the Journaly Editor

#### Ideas / Proposed Solution(s)

- Let's add that as an option
- We should be able to follow existing patterns and reference the Slate docs & examples
- I'll need to add an icon, if someone picks this up in the meantime please tag me here or in the PR and I'll get you an icon 😄

**Comment by davidsonsns** [comment]
Hey @robin-macpherson! Could you assign it to me?

**Comment by robin-macpherson** [comment]
> Hey @robin-macpherson! Could you assign it to me?

@davidsonsns done! Thanks so much for taking this 😄🔥

**Comment by robin-macpherson** [comment]
@davidsonsns I will work on finding a nice icon this evening so that I have it ready for you. By the way, while you're looking into hyperlink capabilities, would it be possible to have a quick look into adding tables for #444 ? Even if it is just to add some extra information to the issue that would be amazing, but of course no worries if you don't have time to look into that

**Comment by davidsonsns** [comment]
Actually, I started this one already! But don't worry about it, because the icon will be pretty easy to change later. Anyways, sounds like slatejs is using a material icon here https://www.slatejs.org/examples/links. Look https://material.io/resources/icons/?icon=link&style=baseline

About the PR #444, I can get it as well tomorrow. Just assign it to me, please 😆

**Comment by robin-macpherson** [comment]
Haha ok amazing, thanks again for all the great work @davidsonsns ! 😆💪🏼
