### ISSUE TITLE
✍🏼 "Suggested replacement" for thread comments

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#477]
Probably a followup to #425 , GH has a very nice "suggestion" function where you can suggest a verbatim change a piece of code. There's a whole functionality for creating commits out of these suggestions that doesn't really apply to us, but just having some formatting to segregate the literal copy someone is suggesting from their general commentary on the highlighted text or the language rule that informs the change would be useful.

Looking at thread comments I see a lot of the following:
- `"<suggested change>" would work better here... <general commentary>`
- `<suggested change>*`
- `<suggested change> (<general commentary>)`
- `<suggested change> <emoji>`

Also not uncommon to see people try to "soften the blow" of a suggestion (last case being an example of this). I think offering a formatting option here would 1. avoid some of the awkward constructs here, 2. reduce the anomie/discomfort of leaving a brief suggestion and help people leave suggestions without needing to manually sugar coat and 3. make suggestions more useful to beginners who may struggle to read suggestions in their target language, clearly separating "here's what you could have written instead" from the "here's why".

Can discuss design and implementation, as a starting point here's a suggestion:

Highlighted text for thread: "I went to the department of fires"

Commenter writes:
```
^ I went to the fire department

In English adjectives appearing before nouns apply to the noun.
```

Commented is rendered as:
```
<small>Suggestion:</small>
<bordered-inset-box>I went to the fire department</bordered-inset-box>
<normal-comment-text>In English adjectives appearing before nouns apply to the noun.</normal-comment-text>
```

Caret syntax is an allusion to like [primary school red pen essay markup shorthand](https://blog.cambridgecoaching.com/hubfs/Red%20Pen.jpg) but definitely negotiable

**Comment by robin-macpherson** [comment]
Love this 💯! I've been thinking about this, too. One thing I thought about was giving people the ability to display ~crossed out text~ to indicate something to be deleted. Another nice thing could be a red highlight for something to be removed and green for something to be added? Seems like we could write a nice and simple diffing algorithm for that to display deletions / additions without much effort, especially given the complexity we already have for diffing all comments on a post with their position. We could use nice, smooth pastel-y colors so that it is visually pleasing and not a super striking red, for example.

This also relates closely to #478 - I think the three issues referenced here (this one, #425 , and #478 ) combined would totally transform the Inline Feedback Experience to being world class 🤓🔥
