### ISSUE TITLE
"read" or "views" count visibility

### ISSUE THREAD

**Issue by ghost** [Journaly/journaly#481]
**Background**
User feedback has been raised today, suggesting _"it would be great to be able to see how many people have read a post, even if they haven’t commented or corrected anything"_

**Perceived Problem**
* Users are unable to see how many people have read their post (vs how many users have actually provided feedback)

**Other Considerations**
* Does this have the potential to send undesirable messaging to the post publisher, as in competitive behaviour or self doubt?
* Does this shape the types of content a publisher would post in the future?
* How would the post publisher use this information?
* Would this be for the post publisher only or all users who click on the post?
* Where would this information be displayed within the post?

**Ideas / Proposed Solution(s)**
* On the specific post's page, add "(insert number) views" totals

**Comment by Lanny** [comment]
I don't have a good case against giving a view count, I guess it could potentially be demotivational to folks who don't get a ton of views but if that's the only concern then we can design around it e.g. not show the count until you have 20 views, or make a "popular" or "trending" indicator that marks posts that have more than X views, basically ways of only calling attention to the stat once it's in the non-demotivational range.

On the other hand I'm not 100% sure there's a goal we really care about that a feature like this would facilitate. Users would probably like it, but it rewards and motivates behavior that draws attention on the feed, not necessarily behavior that produces valuable interaction (like feedback). It might motivate making posts in order to get more views, which is something we'd want to encourage, or it might demonstrate value in showing that users _are_ out there reading out stuff, which is nice, but we also have other ways of doing at least the former (goal setting/tracking, stats like total word count) that might be more direct.

One thing it could be really good for is encouraging users to pull in offsite traffic. Establishing inbound links is really important to SEO, so if people start posting their journaly posts on like, IDK, their study group's forum or twitter or whatever that could be a significant draw to the site, and gamifying post views could encourage that.

IDK, just thinking out loud, definitely open to other opinions. Last point might bring me around on it. It would seem to require building out an internal event tracking system which we could do incrementally, but it wouldn't be a trivial amount of pre-work.

**Comment by robin-macpherson** [comment]
I have lots of thoughts on this one but just chiming in to say that I'm not convinced that we'll want to build this. There are some good points both for and against it and other considerations you've both mentioned, and I'm just thinking a lot about the behaviors and habits we want to train our users with and think this one needs more discussion but lower on the priority list.

Also, an interesting note is that the user who suggested this was essentially complaining that their post had been out for 3 hours and hadn't received any feedback yet, and I believe they did end up getting plenty of feedback even just a few more hours after. It's definitely interesting to see the psychology of different users and I think this kind of feedback will inform a lot of the UX design choices, which is a great feedback loop to have now!

**Comment by robin-macpherson** [comment]
I'm going to close this one as - inline with early discussions on this matter before the issue was created - I don't think it is inline with some of the core goals of Journaly, especially as it relates to our habit-forming design principles and explicitly wanting to be very minimalistic in the features we invest in, and making sure that we aren't building features that mostly encourage the kind of behaviour that ends up diluting the substance of the content on the platform while diminishing the true value Journalers get for the purpose of chasing vanity metrics that won't actually deliver them value.
