### ISSUE TITLE
BUG: General Post Comment Thread - Unable to complete or submit full sentence

### ISSUE THREAD

**Issue by candacepowell** [Journaly/journaly#492]
|                    |                      |
| ------------------ | -------------------- |
| repro              | [link](https://journaly.com/post/3161) |
| `node` version     | `...`                |
| OS and its version |Windows 10|
|Browser|Chrome|

**Description**
User has reported inability to write complete sentence in the General Post comment thread:
_"I wanted to answer to a comment from my Korean post, but it doesn't let me write more than half of the sentence."_

Reviewing the user's post and its comment threads, there is a previous general post comment from the user, so it has worked for them previously. The user said this general post comment was written using the **website**. However, the image provided was from their **mobile**. 

Knowing Issue #479 is currently open, I asked the user to clarify if they could try again on the website (and acknowledged there the IME challenges for mobile as an FYI). They retried, and provided the website image below and were not successful.

In the website image below, it does show a little green refresh symbol, though. Some sort of timeout?

_This has only been reported by a single user so far._ 

**Images:**
Website:
![website](https://user-images.githubusercontent.com/77520576/107113649-630b0280-68b4-11eb-9a50-a32ec1ffcc2b.jpg)

Mobile: Refers to known issue #479 - questionmarksmileyface
![mobile](https://user-images.githubusercontent.com/77520576/107113645-5ab2c780-68b4-11eb-9913-b6f40dce3920.jpg)

**Repro Steps**
1.

**Comment by Lanny** [comment]
I believe the green icon is the grammarly browser extension, which I'm far from sure, but just might be the cause of the issue here.

While I totally see how this looks related, the IME bugs detailed in #479 shouldn't have any relation to issues here, since those are upstream in Slate and we don't use slate for comments. In fact all the comment response box really is is a plain old textarea, which should be pretty reliable and why I suspect grammarly here. We might ask the user to try without grammarly (using a browser that doesn't have it installed or disabling it temporarily). It's a pretty popular extension, so even if it's them breaking us, we would probably still want to find a work around, but a good first step would be to confirm if it really is grammarly playing a role here.

@rickyweb since you're familiar with Korean IME, if you feel like it, could you poke at this and see if you can repro? The critical difference from the prior bug is this is post comments rather than the post editor proper.

**Comment by robin-macpherson** [comment]
Ah yes that's a great point @Lanny ! I've actually noticed the Grammarly extension in a number of screenshots and screen captures that users have sent in. It would be very helpful if we can determine that for certain languages this can cause issues.

**Comment by rickyweb** [comment]
@Lanny I'm sorry, but I have failed to make grammarly work on my firefox, even with an active registration. So I couldn't even try to repro the bug in the comments with grammarly active...

**Comment by Lanny** [comment]
@rickyweb no worries at all. Let's keep an eye on this, see if we get any more reports or hear back from the original reporter

**Comment by candacepowell** [comment]
@Lanny @rickyweb 

The user has replied advising they were able to make a comment in the thread - only by writing the comment in a Word doc and copy-pasting it into the Journaly thread... which was successful. 

I've asked for further Grammarly feedback from them, and awaiting a reply.

**Comment by candacepowell** [comment]
Hi @Lanny , @rickyweb and @robin-macpherson 

Solved. 
This related to Grammarly settings on the user's Grammarly account. Phew! 

Thank you for the time taken on this and I've got this for any further user enquiries of this nature.
