### ISSUE TITLE
More badges for achievements

### ISSUE THREAD

**Issue by Destaq** [Journaly/journaly#525]
I have seen very, very few badges for achievements - only the `Beta User` and `10 posts`. It would be nice if these badges could be fleshed out a bit more, especially as the platform ages and some users write far more than 10 posts.

I'm aware there are also Alpha + Code Contributor badges, but the percentage of users with these is very low and will only decrease with new sign-ups. The jump from 10 posts to 100 posts is a massive one, and I think it would be reasonable to have some more in-between # of post badges such as 25, 50, and 80.

Other badge ideas include:
- writing streak badges
- number of languages written in
- badges for long posts

I hope we can soon see this feature come to Journaly.

**Comment by Lanny** [comment]
Big +1 for this, we threw in the very basic badges we have just to have the system in place but I'm all for expanding. Definitely some good suggestions. Badges for writing streaks and long posts are awesome, and we have other functionality that will require the same groundwork, so those probably go hand in hand. Number of languages with authored posts should be a pretty easy add.

We're in a bit of a holding pattern with things that need migrations because of the payments work that's in progress now, as well as a prisma upgrade we're going to have to do, but we should be good to go pretty soon.

**Comment by Destaq** [comment]
So I have another idea - badges for corrections. Currently, you can't see # of corrections on a user's profile page - it's quite hard to see and only visible at the bottom of their post, on the Author Card.

Therefore, it would be interesting to have badges for the number of corrections given visible on the profile as well; in higher denominations than the number of posts written, of course - maybe something like 20, 50, 100, 250, 500, etc.

Finally a couple non-badge-idea-related thoughts:
- introducing different colors for badges could be a small UI enhancement
- this may be a lot of work, but a way to click on a badge and then see a list of users who have earned it could be very useful; this leaderboard idea could be extended to perhaps an activity/post number leaderboard

**Comment by Lanny** [comment]
Badge idea: get a badge on your first follower

**Comment by LindasLinguas** [comment]
What about a badge for "Top 10 commenters" as a floating badge, meaning that you can loose it when not being so active anymore?

**Comment by robin-macpherson** [comment]
@LindasLinguas that's a nice idea! 😄 I think in general those kind of "floating badges" could be fun. "Most Beloved" something or another for those with the highest number of thanks 😄
