### ISSUE TITLE
Allow users to add/view user interests on settings/profile

### ISSUE THREAD

**Issue by meredithcat** [Journaly/journaly#627]
#### Perceived Problem

Currently, users cannot add or view their interests. Instead, we show hardcoded values of `languages, journaling`.

#### Ideas / Proposed Solution(s)

Adding interests to the user profile flow would require the following:

- Add interests to the prisma schema (looks like this is already done, with the `userInterests` field)
- Update the resolvers to send/receive the user interests in the profile/settings commands
- Add a drop-down for user interests to the settings page, similar to the topic filter in the posts dashboard
- Display user interests on the profile page
- (Optional) Add a "My Interests" filter on the posts dashboard, similar to the "My Languages" filter
  - Would need to decide whether to place it below the topic picker, or below the language picker with the rest of the filters - might become too bloated though if we have too many filters there. Looks like this would fit well with the proposed update in #617.

**Comment by meredithcat** [comment]
I don't think I can assign an issue to myself, but I can take this one on if it's not too urgent. Might be a good one to see how the whole tech stack fits together. @robin-macpherson

**Comment by robin-macpherson** [comment]
@meredithcat this would definitely be a great thing to get done as it's one of the very last core things that doesn't work yet. I should say this one is a little more involved than it first looks due to some updates and improvements we've made to the schema design over time since first modeling the notion of `UserInterests`. You're still welcome to take it on, which would be amazing 💪🏼  But I'd just want to give you some helpful context first and I'd like to potentially propose a few schema changes before we get started.

I was just writing out some context and technical design proposals but it's almost bedtime here and I'm hoping to squeeze in a little Japanese study before bed. If it's okay, I'll come back to you tomorrow with more details 😊
