### ISSUE TITLE
Inline comment box persists even after deleting comment

### ISSUE THREAD

**Issue by meredithcat** [Journaly/journaly#628]
#### Description

As in the screenshot, we still show the highlight & pop-up comment box even for deleted comments. The desired behavior would be to not show it anymore as it could be confusing for the user.

<img width="605" alt="Screen Shot 2021-08-01 at 8 30 19 AM" src="https://user-images.githubusercontent.com/351124/127776571-927692e0-271b-49b1-ba4b-b1a3a9facd51.png">

#### Repro Steps

Leave an inline comment, then delete it.

**Comment by robin-macpherson** [comment]
Hi @meredithcat , the current behaviour is that clicking "cancel" also deletes the comment thread if it is empty. This was something we did in a pinch back in the Alpha testing days due to a variety of reasons/limitations at that time and wanting to at least have some mechanism for those empty threads to be cleaned up, even though it's highly unintuitive. I definitely think it's time to improve that and make the whole thing much more comfortable and intuitive for users 👍🏼
